[package]
name = "launchpad"
version = "0.1.0"
edition = "2021"

[dependencies]
launchpad-macros = { path = "launchpad_macros" }
launchpad-props = { path = "launchpad_props" }
launchpad-router = { path = "launchpad_router" }

bytes = "1.4.0"
tokio = { version = "1.29.1", features = ["full"] }
hyper = { version = "1.0.0-rc.4", features = ["full"] }
http-body-util = "0.1.0-rc.2"

serde_json = "1.0.100"
serde = "1.0.167"
phf = { version = "0.11.2", features = ["macros", "phf_macros"] }

cargo-expand = "1.0.59"
regex = "1.9.1"
serde_qs = "0.12.0"

# Needed for breaking hyper changes - Tokio::io to hyper::rt IO impl's under src/support/*
pin-project-lite = "0.2.10"
futures-util = "0.3.28"
serde_plain = "1.0.1"
