[package]
name = "tela"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Web framework that focuses on ease of use and simplicity"
homepage = "https://tired-fox.github.io/tela/"
documentation = "https://tired-fox.github.io/tela/docs/"
repository = "https://github.com/Tired-Fox/tela"
readme = "README.md"
keywords = ["framework", "web", "server"]
categories = ["web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[patch.crates-io]
tela-macros = { path = 'macros' }

[dependencies]
tela-macros = "0.1.1"
bytes = "1.4.0"
futures = "0.3.28"
futures-util = "0.3.28"
phf = { version = "0.11.2", features = ["macros", "phf_macros"] }

http-body-util = "0.1.0-rc.3"
html-to-string-macro = "0.2.5"
hyper = { version = "1.0.0-rc.4", features=["full"]}
tokio = { version = "1.29.1", features = ["full"] }
tower = { version = "0.4.13", features = ["timeout", "retry", "load", "balance", "buffer", "filter", "limit"] }
mime_guess = "2.0.4"
lazy_static = "1.4.0"
cfg-if = "1.0.0"

pin-project-lite = "0.2.10"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
serde_plain = "1.0.1"
serde_qs = "0.12.0"

tera = { version="1.19.0", optional=true }
handlebars = { version = "4.3.7", features = ["dir_source"], optional = true }

[features]
tera = ["dep:tera"]
handlebars = ["dep:handlebars"]

[[example]]
name = "templates"
required-features = ["tera", "handlebars"]
