[package]
name = "launchpad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
tokio = { version = "1.29.1", features = ["full"] }
hyper = { version = "1.0.0-rc.3", features=["full"]}
http-body-util = "0.1.0-rc.2"
macros = { path = "macros" }
serde_json = "1.0.100"
serde = "1.0.167"
phf = { version = "0.11.2", features = ["macros", "phf_macros"] }
cargo-expand = "1.0.59"
